// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace ML.Model
{
    public class ModelInput
    {
        [ColumnName("Id"), LoadColumn(0)]
        public float Id { get; set; }


        [ColumnName("Lang"), LoadColumn(1)]
        public string Lang { get; set; }


        [ColumnName("Text"), LoadColumn(2)]
        public string Text { get; set; }


    }
}
