// This file was auto-generated by ML.NET Model Builder. 

using System;
using ML.Model;

namespace ML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            string[] _languages = { "en", "es", "de", "tlh" };
            bool continueToRun = true;
            while (continueToRun)
            {
                // Create single instance of sample data from first line of dataset for model input
                Console.Clear();
                Console.WriteLine("Enter a sample to predict:");
                var newSample = Console.ReadLine();
                ModelInput sampleData = new ModelInput()
                {
                    Text = newSample,
                };

                // Make a single prediction on the sample data and print results
                var predictionResult = ConsumeModel.Predict(sampleData);

                Console.WriteLine($"Text: {sampleData.Text}");
                Console.WriteLine($"\n\nPredicted Lang value {predictionResult.Prediction} \nPredicted Lang scores: [{String.Join(",", predictionResult.Score)}]\n\n");
                Console.WriteLine("English: " + predictionResult.Score[0]);
                Console.WriteLine("Español: " + predictionResult.Score[1]);
                Console.WriteLine("Deutsch: " + predictionResult.Score[2]);
                Console.WriteLine("tlhIngan Hol: " + predictionResult.Score[3]);
                Console.WriteLine("Press Enter to continue or Esc to quit");
                ConsoleKeyInfo key = Console.ReadKey();
                if (key.Key == ConsoleKey.Escape)
                {
                    continueToRun = false;
                }
            }

        }
    }
}
